package p2;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MessageBeanEn.java
//  @ Date : 2019-12-03
//  @ Author : 

public class MessageBeanEn implements MessageBean {
	public void sayHello(String name) {
		System.out.println("Hello " + name + "!!!");
	}
}
