//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MessageBean.java
//  @ Date : 2019-12-03
//  @ Author : 
//
//




public class MessageBean {
	public void sayHello(String name) {
	
	}
}
