//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : HelloApp.java
//  @ Date : 2019-12-03
//  @ Author : 
//
//




public class HelloApp {
	public void main(String[] args) {
	
	}
}
