//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : StudentSample.java
//  @ Date : 2019-11-27
//  @ Author : 
//
//

public class StudentSample {
	public static void main(String[] args) {
	
		/*. 
		 * 1. Student shion  -> 객체 변수 선언
		
		2. Student shion=null; -> 객체 변수 선언
		
		1과 2 경우 
		선언된 객체 변수 인수턴스화해서 생성 
		shion = new Student();
		
		3. 객체 변수 인스턴스 생성
		Student shion = new Student();
		*/
		
	Student shion = new Student();
	
	// 입력값을 입력
	shion.setName("홍길동");
	shion.setScore(90);
	
	// 구현된 처리로직을 호출
	shion.printScore();
	
	}
}
