//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : StudentSample.java
//  @ Date : 2019-11-27
//  @ Author : 
//
//

public class StudentSample2 {
	public static void main(String[] args) {
			
	Student shion1 = new Student();
	Student shion2 = new Student();
	
	
	if(shion1==shion2) {
		System.out.println("같다");
	} else {
		System.out.println("다르다");
	}
	
	}
}
