package p1;
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MessageBeanKr.java
//  @ Date : 2019-12-03
//  @ Author : 
//
//




public class MessageBeanKr {
	public void sayHello(String name) {
		System.out.println("гоюл, " + name + "!!!");
	}
}
