package p1;
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MessageBeanEn.java
//  @ Date : 2019-12-03
//  @ Author : 
//
//




public class MessageBeanEn {
	public void sayHello(String name) {
		System.out.println("Hello" + name + "!!!");
	}
}
